// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Database))]
    partial class DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusinessEntity.Customer_Club.ClubDiscount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("RefundToWallet")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("interval");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ClubDiscount");
                });

            modelBuilder.Entity("BusinessEntity.Customer_Club.ClubDiscountProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubDiscountId")
                        .HasColumnType("integer");

                    b.Property<int>("ClubPrice")
                        .HasColumnType("integer");

                    b.Property<int>("OriginalPrice")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClubDiscountId");

                    b.HasIndex("ProductId");

                    b.ToTable("ClubDiscountProduct");
                });

            modelBuilder.Entity("BusinessEntity.Customer_Club.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<int>("CurrentPoints")
                        .HasColumnType("integer");

                    b.Property<int?>("CustomerLevelId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsClubMember")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("LastPurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPurchaseAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalPurchaseCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerLevelId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("BusinessEntity.Customer_Club.CustomerLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxPoints")
                        .HasColumnType("integer");

                    b.Property<int>("MinPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CustomerLevel");
                });

            modelBuilder.Entity("BusinessEntity.Customer_Club.CustomerLevelHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerLevelId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerLevelId");

                    b.ToTable("CustomerLevelHistory");
                });

            modelBuilder.Entity("BusinessEntity.Customer_Club.PointTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("PointTransaction");
                });

            modelBuilder.Entity("BusinessEntity.Customer_Club.PublicDiscount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("Friday")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<bool>("Monday")
                        .HasColumnType("boolean");

                    b.Property<int?>("RecurringDays")
                        .HasColumnType("integer");

                    b.Property<bool>("Saturday")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer");

                    b.Property<bool>("Sunday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Thursday")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("boolean");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("PublicDiscount");
                });

            modelBuilder.Entity("BusinessEntity.Customer_Club.PublicDiscountProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscountedPrice")
                        .HasColumnType("integer");

                    b.Property<int>("OriginalPrice")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("PublicDiscountId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PublicDiscountId");

                    b.ToTable("PublicDiscountProduct");
                });

            modelBuilder.Entity("BusinessEntity.Customer_Club.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Wallet");
                });

            modelBuilder.Entity("BusinessEntity.Customer_Club.WalletTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int?>("ClubDiscountId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClubDiscountId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletTransaction");
                });

            modelBuilder.Entity("BusinessEntity.Fund.Cash_Register_To_The_User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FundId")
                        .HasColumnType("integer");

                    b.Property<long>("InitialAmount")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FundId");

                    b.HasIndex("UserId");

                    b.ToTable("Cash_Register_To_The_User");
                });

            modelBuilder.Entity("BusinessEntity.Fund.Definition_Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("definition_bank", (string)null);
                });

            modelBuilder.Entity("BusinessEntity.Fund.Definition_Bank_Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_number");

                    b.Property<int>("BankId")
                        .HasColumnType("integer");

                    b.Property<string>("BracnhPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("BranchAddres")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BranchId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("card_number");

                    b.Property<bool>("CardReader")
                        .HasColumnType("boolean");

                    b.Property<long>("FirstInventory")
                        .HasColumnType("bigint");

                    b.Property<long>("Inventory")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<int>("NegativeBalancePolicy")
                        .HasColumnType("integer");

                    b.Property<string>("PeopleAccount")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("people_account");

                    b.Property<string>("TypeAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type_account");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BankId");

                    b.ToTable("definition_bank_account", (string)null);
                });

            modelBuilder.Entity("BusinessEntity.Fund.Fund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("FirstInventory")
                        .HasColumnType("bigint");

                    b.Property<long>("Inventory")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NegativeBalancePolicy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Fund");
                });

            modelBuilder.Entity("BusinessEntity.Fund.Work_Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CashRegisterToUserId")
                        .HasColumnType("integer");

                    b.Property<long>("ClosingAmount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAuto")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<long>("OpeningAmount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CashRegisterToUserId");

                    b.ToTable("Work_Shift");
                });

            modelBuilder.Entity("BusinessEntity.Invoices.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.HasKey("AccountId");

                    b.HasIndex("AccountName")
                        .IsUnique();

                    b.ToTable("Account");
                });

            modelBuilder.Entity("BusinessEntity.Invoices.Invoices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubDiscountAll")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int?>("CustomerLevelId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EarnedPoints")
                        .HasColumnType("integer");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsClubDiscountRefunded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUpdate")
                        .HasColumnType("boolean");

                    b.Property<int>("LevelDiscountAmount")
                        .HasColumnType("integer");

                    b.Property<int>("NumberofAllItems")
                        .HasColumnType("integer");

                    b.Property<int>("OffAll")
                        .HasColumnType("integer");

                    b.Property<int>("PeopleId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSum")
                        .HasColumnType("integer");

                    b.Property<int>("TyepPay")
                        .HasColumnType("integer");

                    b.Property<int>("TypeInvoices")
                        .HasColumnType("integer");

                    b.Property<int>("UsedWalletAmount")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerLevelId");

                    b.HasIndex("PeopleId");

                    b.HasIndex("UserId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("BusinessEntity.Invoices.Invoices_Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AllPrice")
                        .HasColumnType("integer");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClubDiscount")
                        .HasColumnType("integer");

                    b.Property<int?>("ClubDiscountId")
                        .HasColumnType("integer");

                    b.Property<int>("InvoicesId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("OFF")
                        .HasColumnType("integer");

                    b.Property<int>("OriginalPrice")
                        .HasColumnType("integer");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("PublicDiscountId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClubDiscountId");

                    b.HasIndex("InvoicesId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PublicDiscountId");

                    b.ToTable("Invoices_Item");
                });

            modelBuilder.Entity("BusinessEntity.Invoices.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<int?>("RelatedAccountId")
                        .HasColumnType("integer");

                    b.Property<int?>("RelatedDocumentId")
                        .HasColumnType("integer");

                    b.Property<string>("RelatedDocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WorkShiftId")
                        .HasColumnType("integer");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountId");

                    b.HasIndex("WorkShiftId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("BusinessEntity.People.Group_People", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Group_People");
                });

            modelBuilder.Entity("BusinessEntity.People.People", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Business")
                        .HasColumnType("boolean");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Employee")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("GroupPeopleId")
                        .HasColumnType("integer");

                    b.Property<int>("HowToDoBusiness")
                        .HasColumnType("integer");

                    b.Property<string>("IdPeople")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InitialCapital")
                        .HasColumnType("integer");

                    b.Property<long>("Inventory")
                        .HasColumnType("bigint");

                    b.Property<bool>("Investor")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCreditLimit")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("OFF")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<int>("PriceLevelID")
                        .HasColumnType("integer");

                    b.Property<bool>("TaxFree")
                        .HasColumnType("boolean");

                    b.Property<int>("TypePeopleId")
                        .HasColumnType("integer");

                    b.Property<bool>("User")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("GroupPeopleId");

                    b.HasIndex("PriceLevelID");

                    b.HasIndex("TypePeopleId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("BusinessEntity.People.Type_People", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Type_People");
                });

            modelBuilder.Entity("BusinessEntity.Product.Group_Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Group_Product");
                });

            modelBuilder.Entity("BusinessEntity.Product.PriceLevels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("PriceLevels");
                });

            modelBuilder.Entity("BusinessEntity.Product.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GroupProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Inventory")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBarcode")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsIsButton")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTax")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWeighty")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxInventory")
                        .HasColumnType("integer");

                    b.Property<int>("MinInventory")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Profit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SectionProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ShortcutKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StoreroomProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tax")
                        .HasColumnType("numeric");

                    b.Property<int>("TypeProductId")
                        .HasColumnType("integer");

                    b.Property<int>("UnitProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupProductId");

                    b.HasIndex("SectionProductId");

                    b.HasIndex("StoreroomProductId");

                    b.HasIndex("TypeProductId");

                    b.HasIndex("UnitProductId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("BusinessEntity.Product.ProductBarcodes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("ProductUnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductUnitId");

                    b.ToTable("ProductBarcodes");
                });

            modelBuilder.Entity("BusinessEntity.Product.ProductPrices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PriceLevelId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Profit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitLevelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PriceLevelId");

                    b.HasIndex("UnitLevelId");

                    b.ToTable("ProductPrices");
                });

            modelBuilder.Entity("BusinessEntity.Product.Product_Failure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Product_Failure");
                });

            modelBuilder.Entity("BusinessEntity.Product.Product_Failure_Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ProductFailureId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("StoreroomId")
                        .HasColumnType("integer");

                    b.Property<int?>("Storeroom_ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductFailureId");

                    b.HasIndex("ProductId");

                    b.HasIndex("Storeroom_ProductId");

                    b.ToTable("Product_Failure_Item");
                });

            modelBuilder.Entity("BusinessEntity.Product.Section_Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Section_Product");
                });

            modelBuilder.Entity("BusinessEntity.Product.Storeroom_Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NegativeBalancePolicy")
                        .HasColumnType("integer");

                    b.Property<int>("PeopleId")
                        .HasColumnType("integer");

                    b.Property<int>("SectionProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PeopleId");

                    b.HasIndex("SectionProductId");

                    b.ToTable("Storeroom_Product");
                });

            modelBuilder.Entity("BusinessEntity.Product.Type_Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Type_Product");
                });

            modelBuilder.Entity("BusinessEntity.Product.Unit_Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Unit_Product");
                });

            modelBuilder.Entity("BusinessEntity.Product.UnitsLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConversionFactor")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnitProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitProductId");

                    b.ToTable("UnitsLevel");
                });

            modelBuilder.Entity("BusinessEntity.Settings.Access_Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupUserId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAccessLevel")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBank")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBankT")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFund")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGroupPeople")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGroupProduct")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGroupUser")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInvoices")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPeople")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPriceLevel")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProduct")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProductFailre")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRegisterUser")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSectionProduct")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStoreroomProduct")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTypePeopel")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTypeProduct")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUnitProduct")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUser")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsViewingofOthers")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWorkShift")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GroupUserId")
                        .IsUnique();

                    b.ToTable("Access_Level");
                });

            modelBuilder.Entity("BusinessEntity.Settings.Group_User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Access_LevelId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Access_LevelId");

                    b.ToTable("Group_User");
                });

            modelBuilder.Entity("BusinessEntity.Settings.LogUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LogUser");
                });

            modelBuilder.Entity("BusinessEntity.Settings.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reminder");
                });

            modelBuilder.Entity("BusinessEntity.Settings.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentSessionId")
                        .HasColumnType("text");

                    b.Property<int>("GroupUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PeopleId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("Validity")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GroupUserId");

                    b.HasIndex("PeopleId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("BusinessEntity.Customer_Club.ClubDiscountProduct", b =>
                {
                    b.HasOne("BusinessEntity.Customer_Club.ClubDiscount", "ClubDiscount")
                        .WithMany("Products")
                        .HasForeignKey("ClubDiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessEntity.Product.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClubDiscount");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BusinessEntity.Customer_Club.Customer", b =>
                {
                    b.HasOne("BusinessEntity.Customer_Club.CustomerLevel", "CustomerLevel")
                        .WithMany("Customers")
                        .HasForeignKey("CustomerLevelId");

                    b.Navigation("CustomerLevel");
                });

            modelBuilder.Entity("BusinessEntity.Customer_Club.CustomerLevelHistory", b =>
                {
                    b.HasOne("BusinessEntity.Customer_Club.Customer", "Customer")
                        .WithMany("LevelHistories")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessEntity.Customer_Club.CustomerLevel", "CustomerLevel")
                        .WithMany("LevelHistories")
                        .HasForeignKey("CustomerLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("CustomerLevel");
                });

            modelBuilder.Entity("BusinessEntity.Customer_Club.PointTransaction", b =>
                {
                    b.HasOne("BusinessEntity.Customer_Club.Customer", "Customer")
                        .WithMany("PointTransactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessEntity.Invoices.Invoices", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId");

                    b.Navigation("Customer");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("BusinessEntity.Customer_Club.PublicDiscountProduct", b =>
                {
                    b.HasOne("BusinessEntity.Product.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessEntity.Customer_Club.PublicDiscount", "PublicDiscount")
                        .WithMany("Products")
                        .HasForeignKey("PublicDiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PublicDiscount");
                });

            modelBuilder.Entity("BusinessEntity.Customer_Club.Wallet", b =>
                {
                    b.HasOne("BusinessEntity.Customer_Club.Customer", "Customer")
                        .WithOne("Wallet")
                        .HasForeignKey("BusinessEntity.Customer_Club.Wallet", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BusinessEntity.Customer_Club.WalletTransaction", b =>
                {
                    b.HasOne("BusinessEntity.Customer_Club.ClubDiscount", "ClubDiscount")
                        .WithMany()
                        .HasForeignKey("ClubDiscountId");

                    b.HasOne("BusinessEntity.Invoices.Invoices", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId");

                    b.HasOne("BusinessEntity.Customer_Club.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClubDiscount");

                    b.Navigation("Invoice");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("BusinessEntity.Fund.Cash_Register_To_The_User", b =>
                {
                    b.HasOne("BusinessEntity.Fund.Fund", "Fund")
                        .WithMany("CashRegisters")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessEntity.Settings.User", "User")
                        .WithMany("CashRegisters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fund");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessEntity.Fund.Definition_Bank_Account", b =>
                {
                    b.HasOne("BusinessEntity.Invoices.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessEntity.Fund.Definition_Bank", "Bank")
                        .WithMany("BankAccounts")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("BusinessEntity.Fund.Fund", b =>
                {
                    b.HasOne("BusinessEntity.Invoices.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessEntity.Fund.Work_Shift", b =>
                {
                    b.HasOne("BusinessEntity.Fund.Cash_Register_To_The_User", "CashRegisterToUser")
                        .WithMany("WorkShifts")
                        .HasForeignKey("CashRegisterToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CashRegisterToUser");
                });

            modelBuilder.Entity("BusinessEntity.Invoices.Invoices", b =>
                {
                    b.HasOne("BusinessEntity.Customer_Club.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessEntity.Customer_Club.CustomerLevel", "CustomerLevel")
                        .WithMany()
                        .HasForeignKey("CustomerLevelId");

                    b.HasOne("BusinessEntity.People.People", "People")
                        .WithMany("Invoices")
                        .HasForeignKey("PeopleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessEntity.Settings.User", "User")
                        .WithMany("Invoices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("CustomerLevel");

                    b.Navigation("People");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessEntity.Invoices.Invoices_Item", b =>
                {
                    b.HasOne("BusinessEntity.Customer_Club.ClubDiscount", "ClubDiscountEntity")
                        .WithMany()
                        .HasForeignKey("ClubDiscountId");

                    b.HasOne("BusinessEntity.Invoices.Invoices", "Invoices")
                        .WithMany("Invoices_Item")
                        .HasForeignKey("InvoicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessEntity.Product.Product", "Product")
                        .WithMany("Invoices_Items")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessEntity.Customer_Club.PublicDiscount", "PublicDiscount")
                        .WithMany()
                        .HasForeignKey("PublicDiscountId");

                    b.Navigation("ClubDiscountEntity");

                    b.Navigation("Invoices");

                    b.Navigation("Product");

                    b.Navigation("PublicDiscount");
                });

            modelBuilder.Entity("BusinessEntity.Invoices.Transaction", b =>
                {
                    b.HasOne("BusinessEntity.Invoices.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessEntity.Fund.Work_Shift", "WorkShift")
                        .WithMany()
                        .HasForeignKey("WorkShiftId");

                    b.Navigation("Account");

                    b.Navigation("WorkShift");
                });

            modelBuilder.Entity("BusinessEntity.People.People", b =>
                {
                    b.HasOne("BusinessEntity.Invoices.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessEntity.People.Group_People", "Group_People")
                        .WithMany("People")
                        .HasForeignKey("GroupPeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessEntity.Product.PriceLevels", "PriceLevel")
                        .WithMany("People")
                        .HasForeignKey("PriceLevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessEntity.People.Type_People", "Type_People")
                        .WithMany("People")
                        .HasForeignKey("TypePeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Group_People");

                    b.Navigation("PriceLevel");

                    b.Navigation("Type_People");
                });

            modelBuilder.Entity("BusinessEntity.Product.Product", b =>
                {
                    b.HasOne("BusinessEntity.Product.Group_Product", "GroupProduct")
                        .WithMany("Products")
                        .HasForeignKey("GroupProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessEntity.Product.Section_Product", "SectionProduct")
                        .WithMany("Products")
                        .HasForeignKey("SectionProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessEntity.Product.Storeroom_Product", "StoreroomProduct")
                        .WithMany("Products")
                        .HasForeignKey("StoreroomProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessEntity.Product.Type_Product", "TypeProduct")
                        .WithMany("Products")
                        .HasForeignKey("TypeProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessEntity.Product.Unit_Product", "Unit_Product")
                        .WithMany("Products")
                        .HasForeignKey("UnitProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupProduct");

                    b.Navigation("SectionProduct");

                    b.Navigation("StoreroomProduct");

                    b.Navigation("TypeProduct");

                    b.Navigation("Unit_Product");
                });

            modelBuilder.Entity("BusinessEntity.Product.ProductBarcodes", b =>
                {
                    b.HasOne("BusinessEntity.Product.UnitsLevel", "ProductUnit")
                        .WithMany("Barcodes")
                        .HasForeignKey("ProductUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductUnit");
                });

            modelBuilder.Entity("BusinessEntity.Product.ProductPrices", b =>
                {
                    b.HasOne("BusinessEntity.Product.PriceLevels", "PriceLevel")
                        .WithMany("ProductPrices")
                        .HasForeignKey("PriceLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessEntity.Product.UnitsLevel", "ProductUnit")
                        .WithMany("Prices")
                        .HasForeignKey("UnitLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceLevel");

                    b.Navigation("ProductUnit");
                });

            modelBuilder.Entity("BusinessEntity.Product.Product_Failure_Item", b =>
                {
                    b.HasOne("BusinessEntity.Product.Product_Failure", "ProductFailure")
                        .WithMany("ProductFailureItems")
                        .HasForeignKey("ProductFailureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessEntity.Product.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("BusinessEntity.Product.Storeroom_Product", "Storeroom_Product")
                        .WithMany()
                        .HasForeignKey("Storeroom_ProductId");

                    b.Navigation("Product");

                    b.Navigation("ProductFailure");

                    b.Navigation("Storeroom_Product");
                });

            modelBuilder.Entity("BusinessEntity.Product.Storeroom_Product", b =>
                {
                    b.HasOne("BusinessEntity.People.People", "People")
                        .WithMany("Storeroom_Product")
                        .HasForeignKey("PeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessEntity.Product.Section_Product", "Section_Product")
                        .WithMany("Storeroom_Product")
                        .HasForeignKey("SectionProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("People");

                    b.Navigation("Section_Product");
                });

            modelBuilder.Entity("BusinessEntity.Product.UnitsLevel", b =>
                {
                    b.HasOne("BusinessEntity.Product.Product", "Product")
                        .WithMany("Units")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessEntity.Product.Unit_Product", "UnitProduct")
                        .WithMany("UnitsLevel")
                        .HasForeignKey("UnitProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("UnitProduct");
                });

            modelBuilder.Entity("BusinessEntity.Settings.Access_Level", b =>
                {
                    b.HasOne("BusinessEntity.Settings.Group_User", "Group_User")
                        .WithOne("AccessLevel")
                        .HasForeignKey("BusinessEntity.Settings.Access_Level", "GroupUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group_User");
                });

            modelBuilder.Entity("BusinessEntity.Settings.Group_User", b =>
                {
                    b.HasOne("BusinessEntity.Settings.Access_Level", null)
                        .WithMany("Groups")
                        .HasForeignKey("Access_LevelId");
                });

            modelBuilder.Entity("BusinessEntity.Settings.LogUser", b =>
                {
                    b.HasOne("BusinessEntity.Settings.User", "User")
                        .WithMany("LogUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessEntity.Settings.Reminder", b =>
                {
                    b.HasOne("BusinessEntity.Settings.User", "User")
                        .WithMany("Reminders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessEntity.Settings.User", b =>
                {
                    b.HasOne("BusinessEntity.Settings.Group_User", "Group_User")
                        .WithMany("Users")
                        .HasForeignKey("GroupUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessEntity.People.People", "People")
                        .WithMany("Users")
                        .HasForeignKey("PeopleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group_User");

                    b.Navigation("People");
                });

            modelBuilder.Entity("BusinessEntity.Customer_Club.ClubDiscount", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BusinessEntity.Customer_Club.Customer", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("LevelHistories");

                    b.Navigation("PointTransactions");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("BusinessEntity.Customer_Club.CustomerLevel", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("LevelHistories");
                });

            modelBuilder.Entity("BusinessEntity.Customer_Club.PublicDiscount", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BusinessEntity.Customer_Club.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BusinessEntity.Fund.Cash_Register_To_The_User", b =>
                {
                    b.Navigation("WorkShifts");
                });

            modelBuilder.Entity("BusinessEntity.Fund.Definition_Bank", b =>
                {
                    b.Navigation("BankAccounts");
                });

            modelBuilder.Entity("BusinessEntity.Fund.Fund", b =>
                {
                    b.Navigation("CashRegisters");
                });

            modelBuilder.Entity("BusinessEntity.Invoices.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BusinessEntity.Invoices.Invoices", b =>
                {
                    b.Navigation("Invoices_Item");
                });

            modelBuilder.Entity("BusinessEntity.People.Group_People", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("BusinessEntity.People.People", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Storeroom_Product");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BusinessEntity.People.Type_People", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("BusinessEntity.Product.Group_Product", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BusinessEntity.Product.PriceLevels", b =>
                {
                    b.Navigation("People");

                    b.Navigation("ProductPrices");
                });

            modelBuilder.Entity("BusinessEntity.Product.Product", b =>
                {
                    b.Navigation("Invoices_Items");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("BusinessEntity.Product.Product_Failure", b =>
                {
                    b.Navigation("ProductFailureItems");
                });

            modelBuilder.Entity("BusinessEntity.Product.Section_Product", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Storeroom_Product");
                });

            modelBuilder.Entity("BusinessEntity.Product.Storeroom_Product", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BusinessEntity.Product.Type_Product", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BusinessEntity.Product.Unit_Product", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("UnitsLevel");
                });

            modelBuilder.Entity("BusinessEntity.Product.UnitsLevel", b =>
                {
                    b.Navigation("Barcodes");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("BusinessEntity.Settings.Access_Level", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("BusinessEntity.Settings.Group_User", b =>
                {
                    b.Navigation("AccessLevel");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BusinessEntity.Settings.User", b =>
                {
                    b.Navigation("CashRegisters");

                    b.Navigation("Invoices");

                    b.Navigation("LogUser");

                    b.Navigation("Reminders");
                });
#pragma warning restore 612, 618
        }
    }
}
