name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 185.126.2.237
          username: parang
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            cd ~/prime-sofwere
            git fetch --all
            git reset --hard origin/main
            cd "Prime Software"
            /usr/share/dotnet/dotnet clean
            /usr/share/dotnet/dotnet publish -c Release -o out
            sudo systemctl restart prime-software